dist: xenial

language: php

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  include:
    - php: 7.2
      dist: xenial

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/athletic --path test/Benchmark --formatter GroupedFormatter
